[package]
name = "aoc2022-22"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
glam = "0.22.0"
itertools = "0.10.5"
pest = "2.5.1"
pest_derive = "2.5.1"
